#! /bin/sh

CUR_DIR=$PWD
PID_FILE="$CUR_DIR/node.pid"
NODE_JOBS_FILE="/usr/local/node.jobs/jobs_server.js"

case "$1" in
    start)
	if [ -e $PID_FILE ]; then
		echo "Node.js is already running."
	else
		echo "Starting Node.Jobs Server"
		(sudo -u www-data node $NODE_JOBS_FILE >> /var/log/node.jobs/access.log &) && ps -C node | cut -d"
" -f 2 | cut -d" " -f 1 > $PID_FILE
	fi
        ;;
    stop)
	if [ ! -e $PID_FILE ]; then
		echo "Node.js is not running."
	else
		echo "Stopping Node.Jobs Server"
		kill `cat $PID_FILE`
		rm -rf $PID_FILE
	fi
        ;;
esac

exit 0

